# Generated by Django 5.2.5 on 2025-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_brother', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='number_id',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
